project/urls.py
from django.contrib import admin
from django.urls import include, path

from task.views import home

app_name = 'base'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name="home"),
    path('task/', include('task.urls')),
]

task/urls.py
from django.urls import path

from project.urls import home

from . import views

app_name = 'task'

urlpatterns = [
    path('create/', views.create_task, name="create_task"),
    path('', home, name="home"),
    path('update/<int:id>', views.update_task, name="update_task"),
    path('delete/<int:id>', views.delete_task, name="delete_task"),
]

task/models.py
from django.db import models

# Create your models here.


class task(models.Model):
    def __str__(self):
        return self.title
    title = models.CharField(max_length=255)
    date = models.DateField(
        auto_now=False, auto_now_add=False)

task/views.py

from datetime import date

from django.shortcuts import render

from task.models import task

# Create your views here.

start_date = date.today()


def create_task(request):

    if request.method == 'GET':
        return render(request, 'task/pages/create.html')
    else:
        title = request.POST.get('title')
        date_form = request.POST.get('date')
        add = task.objects.create(title=title, date=date_form)
        add.save()
        return render(request, 'task/pages/create.html', context={
            'date': start_date
        })


def update_task(request, id):
    task_info = task.objects.get(id=id)
    if request.method == "GET":
        return render(request, 'task/pages/update.html', context={
            'task': task_info,
            'date': start_date,
        })

    # else:


def home(request):
    task_ = task.objects.all().order_by('-id')
    context = {
        'task': task_
    }
    return render(request, 'task/pages/home.html', context=context)


def delete_task(request, id):
    if request.method == 'GET':
        return render(request, 'task/pages/delete.html')

    else:
        task_ = task.objects.all().order_by('-id')
        context = {
            'task': task_
        }
        deleting = task.objects.get(pk=id)

        deleting.delete()
        return render(request, 'task/pages/home.html', context=context)

task/templates/task/pages/create.html
{% extends 'global/base.html' %}
{% block title %} | Create task{% endblock title %}
{% block content %}
    <div class="form-container">
        <form method="post">
            {% csrf_token %}
            <h1>Create new task</h1>
            <label for="task">Title</label>
            <input type="text" name="title" required>
            <label for="date">Date</label>
            <input type="date" start="{{ date.date }}" value="03-03-2003" name="date" id="date" required>
            <button class="btn btn-create" type="submit">Save</button>
        </form>
    </div>
{% endblock content %}

task/templates/task/pages/delete.html
{% extends 'global/base.html' %}
{% block content %}
<div class="choices">
    <h1>You are about to delete your task. Do you sure want to continue?</h1>
    <form method="POST" >
        {% csrf_token %}
        <input class="btn btn-yes" type="submit" name="yes" value="Yes"></input>
        <a class="no" href="{% url 'task:home' %}" >No</a>
    </form>
</div>
{% endblock content %}

task/templates/task/pages/home.html
{% extends 'global/base.html' %}
{% block title %} | Home{% endblock title %}
{% block content %}
 <div class="item">
     <table>
         <tr>
             <th>Title</th>
             <th>Date</th>
            </tr>
            {% for items in task %}
    <tr>
        <td> {{ items.title }} </td>
        <td> {{ items.date }} </td>
        <td class="options-list"><a href="{% url 'task:delete_task' items.id %}">X</a></td>
        <td class="options-list"><a href="{% url 'task:update_task' items.id %}">U</a></td>
    </tr>
    {% empty %}
    <h1>Sorry, you still didn't add a task</h1>
    {% endfor %}
</table>    
</div> 

{% endblock content %}

task/templates/task/pages/update.html
{% extends 'global/base.html' %}
{% block title %} | Update task{% endblock title %}
{% block content %}
    <div class="form-container">
        <form method="post">
            <h1>Update task</h1>
            <label for="task">Title</label>
            <input type="text" name="task" required value="{{task.title}}">
            <label for="date">Date</label>
            <input type="date" name="date" id="date" value="{{ task.date }}" required>
            <button class="btn btn-create" type="submit">Save changes</button>
        </form>
    </div>
{% endblock content %}